name: Go Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v -o floyd-weather-server

    - name: Test
      run: |
        # Basic syntax check with go vet
        go vet ./...
        
        # Allow test to complete even if API calls fail
        echo '{"method":"get-weather","parameters":{"city":"London","country":"United Kingdom"}}' | ./floyd-weather-server || true
